// Naccache-Whelan bar-width attack — enumerates candidate strings whose total advance width
// matches a redaction bar, exploiting the fact that bar width encodes character-sequence width.

import type { FontMetrics } from '../font/metrics.js';

/** A candidate string generated by the Naccache-Whelan enumeration. */
export interface Candidate {
	/** The candidate text. */
	text: string;
	/** Absolute difference in PDF units between the candidate's rendered width and the target bar. */
	widthError: number;
	/** Relative likelihood score 0–1 based on width match and character frequency. */
	probability: number;
}

export interface NaccacheWhelanOptions {
	/** Width of the redaction bar in PDF user-space units. */
	barWidth: number;
	/** Font metrics used to compute advance widths. */
	metrics: FontMetrics;
	/** Active font size in PDF units. */
	fontSize: number;
	/** Fraction of barWidth accepted as tolerance. Default: 0.03 (3%). */
	tolerance?: number;
	/** Maximum candidates to return. Default: 50. */
	maxCandidates?: number;
	/** Surrounding text before the redaction for plausibility filtering. */
	contextBefore?: string;
	/** Surrounding text after the redaction for plausibility filtering. */
	contextAfter?: string;
}

// ---------------------------------------------------------------------------
// Built-in word list (legal, common English, names, temporal)
// ---------------------------------------------------------------------------

const WORD_LIST: readonly string[] = [
	// Common English words
	'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'it', 'for', 'not', 'on',
	'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his', 'by', 'from', 'they',
	'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there',
	'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go', 'me',
	'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people',
	'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than', 'then',
	'now', 'look', 'only', 'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use',
	'two', 'how', 'our', 'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any',
	'these', 'give', 'day', 'most', 'us', 'between', 'may', 'down', 'free', 'has', 'been',
	// Legal / document terms
	'plaintiff', 'defendant', 'court', 'case', 'judge', 'order', 'exhibit', 'counsel',
	'attorney', 'motion', 'claim', 'filed', 'action', 'legal', 'contract', 'agreement',
	'party', 'parties', 'evidence', 'witness', 'testimony', 'deposition', 'complaint',
	'answer', 'discovery', 'verdict', 'settlement', 'damages', 'liability', 'breach',
	'statute', 'regulation', 'amendment', 'section', 'clause', 'provision', 'pursuant',
	'redacted', 'classified', 'confidential', 'privileged', 'protected', 'sealed',
	'exempt', 'exemption', 'withheld', 'privilege', 'responsive', 'relevant',
	// Names (common US first names)
	'John', 'Jane', 'James', 'Mary', 'Robert', 'Patricia', 'Michael', 'Jennifer',
	'William', 'Linda', 'David', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica',
	'Thomas', 'Sarah', 'Charles', 'Karen', 'Christopher', 'Nancy', 'Daniel', 'Lisa',
	'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra', 'Donald', 'Ashley',
	'Steven', 'Dorothy', 'Paul', 'Kimberly', 'Andrew', 'Emily', 'Joshua', 'Donna',
	'Kenneth', 'Michelle', 'Kevin', 'Carol', 'Brian', 'Amanda', 'George', 'Melissa',
	'Timothy', 'Deborah', 'Ronald', 'Stephanie', 'Edward', 'Rebecca', 'Jason', 'Sharon',
	'Jeffrey', 'Laura', 'Ryan', 'Cynthia', 'Jacob', 'Kathleen', 'Gary', 'Amy', 'Nicholas',
	// Common last names
	'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
	'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson',
	'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Perez', 'Thompson',
	'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker',
	'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
	'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell',
	// Months and days
	'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August',
	'September', 'October', 'November', 'December',
	'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
	// US states
	'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
	'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
	'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
	'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
	'New York', 'New Jersey', 'Texas', 'Ohio', 'Virginia', 'Washington',
	// Numbers (written out)
	'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
	'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'twenty', 'thirty', 'forty',
	'fifty', 'hundred', 'thousand', 'million', 'billion',
	// Common adjectives/verbs in legal/government docs
	'alleged', 'criminal', 'civil', 'federal', 'national', 'public', 'private', 'secret',
	'unknown', 'identified', 'unidentified', 'involved', 'related', 'alleged', 'reported',
	'investigation', 'agency', 'department', 'government', 'official', 'agent', 'officer',
	'individual', 'person', 'address', 'location', 'information', 'document', 'record',
	// Single uppercase letters / abbreviations
	'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
	'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
	'FBI', 'CIA', 'NSA', 'DOJ', 'DOD', 'EPA', 'IRS', 'SSN', 'USA', 'NYC', 'LA',
];

/** English letter bigram frequency table for scoring (higher = more common). */
const BIGRAM_SCORES: Readonly<Record<string, number>> = {
	th: 10, he: 9, in: 9, er: 8, an: 8, re: 8, on: 7, en: 7, at: 7, es: 7,
	st: 7, to: 7, nt: 6, or: 6, nd: 6, is: 6, ar: 6, al: 6, it: 6, as: 6,
};

/** Compute a character frequency score for a candidate string (0–1). */
function scoreByFrequency(text: string): number {
	if (text.length < 2) return 0.3;
	let score = 0;
	const lower = text.toLowerCase();
	for (let i = 0; i < lower.length - 1; i++) {
		const bigram = lower.slice(i, i + 2);
		score += BIGRAM_SCORES[bigram] ?? 0;
	}
	// Normalise — max possible ~10 per bigram * (len-1) bigrams
	return Math.min(1, score / (10 * (lower.length - 1)));
}

/**
 * Enumerate candidate strings whose rendered width at `fontSize` matches `barWidth`
 * within the given tolerance.
 *
 * Uses the Naccache-Whelan observation: the total width of a redaction bar encodes
 * the sum of advance widths of the redacted characters at the active font size.
 */
export async function enumerateCandidates(options: NaccacheWhelanOptions): Promise<Candidate[]> {
	const {
		barWidth,
		metrics,
		fontSize,
		tolerance = 0.03,
		maxCandidates = 50,
	} = options;

	if (barWidth <= 0 || fontSize <= 0) return [];

	const toleranceUnits = barWidth * tolerance;
	const candidates: Candidate[] = [];

	for (const word of WORD_LIST) {
		const renderedWidth = metrics.stringWidth(word, fontSize);
		const error = Math.abs(renderedWidth - barWidth);
		if (error <= toleranceUnits) {
			candidates.push({
				text: word,
				widthError: error,
				probability: 0, // set below
			});
		}
	}

	// Also enumerate short digit strings (phone, SSN fragments, years, IDs)
	const avgCharWidth = metrics.stringWidth('0123456789', fontSize) / 10;
	if (avgCharWidth > 0) {
		const estimatedLen = Math.round(barWidth / avgCharWidth);
		for (let len = Math.max(1, estimatedLen - 2); len <= estimatedLen + 2; len++) {
			for (const digits of generateDigitCandidates(len)) {
				const renderedWidth = metrics.stringWidth(digits, fontSize);
				const error = Math.abs(renderedWidth - barWidth);
				if (error <= toleranceUnits) {
					candidates.push({ text: digits, widthError: error, probability: 0 });
				}
			}
		}
	}

	// Score and deduplicate
	const seen = new Set<string>();
	const scored: Candidate[] = [];
	for (const c of candidates) {
		if (seen.has(c.text)) continue;
		seen.add(c.text);
		const widthScore = 1 - c.widthError / (barWidth * tolerance + 1);
		const freqScore = scoreByFrequency(c.text);
		scored.push({ ...c, probability: widthScore * 0.6 + freqScore * 0.4 });
	}

	scored.sort((a, b) => b.probability - a.probability);
	return scored.slice(0, maxCandidates);
}

/** Generate a small set of representative digit strings of given length. */
function* generateDigitCandidates(len: number): Generator<string> {
	if (len <= 0) return;
	// Common year range
	if (len === 4) {
		for (let y = 1950; y <= 2030; y++) yield String(y);
		return;
	}
	// Sample numeric patterns
	if (len <= 3) {
		for (let n = 0; n < Math.min(999, 10 ** len); n++) {
			yield String(n).padStart(len, '0');
		}
	}
}
